# Generated by Django 5.1.7 on 2025-03-17 00:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='quit_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='smoking_goal',
        ),
        migrations.CreateModel(
            name='QuittingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, help_text='The start date of the quitting plan.')),
                ('duration', models.PositiveIntegerField(help_text='Duration of the quitting plan in days.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SmokingHabits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cigs_per_day', models.PositiveIntegerField(help_text='How manycigarettes do you smoke per day?')),
                ('cigs_per_pack', models.PositiveIntegerField(help_text='How many cigarettes are in one pack?')),
                ('pack_cost', models.DecimalField(decimal_places=2, help_text='Cost of one pack.', max_digits=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
