# Generated by Django 5.1.7 on 2025-03-17 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_customuser_quit_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smokinghabits',
            name='cigs_per_day',
            field=models.PositiveIntegerField(help_text='How many cigarettes do you smoke per day?'),
        ),
    ]
